<?php
/**
 * WeCodeArt Framework.
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package 	WeCodeArt Framework
 * @subpackage 	Support\Modules\Formatting
 * @copyright   Copyright (c) 2024, WeCodeArt Framework
 * @since 		6.6.0
 * @version		6.6.0
 */

namespace WeCodeArt\Support\Modules;

defined( 'ABSPATH' ) || exit;

use WeCodeArt\Config\Traits\{ Asset, Singleton, No_Conditionals };
use WeCodeArt\Config\Interfaces\Integration;
use WeCodeart\Gutenberg\Patterns;

/**
 * The Tabs object.
 */
final class Tabs implements Integration {

    use Asset;
    use Singleton;
	use No_Conditionals;

	const VERSION = '1.0.0';

	/**
	 * Send to Constructor
	 */
	public function register_hooks() {
		\add_action( 'init', [ $this, 'register_blocks' ], 20, 1 );

		if( apply_filters( 'wecodeart/filter/modules/tabs/patterns', true ) ) {
			\add_action( 'init', [ $this, 'register_patterns' ], 20, 1 );
		}
	}

	/**
	 * Register block.
	 *
	 * @return  void
	 */
	public function register_blocks(): void {
		\register_block_type_from_metadata( dirname( __FILE__ ) . '/blocks/tabs-block.json' );
		\register_block_type_from_metadata( dirname( __FILE__ ) . '/blocks/tabs-nav-block.json' );
		\register_block_type_from_metadata( dirname( __FILE__ ) . '/blocks/tabs-nav-item-block.json' );
		\register_block_type_from_metadata( dirname( __FILE__ ) . '/blocks/tabs-panel-block.json' );
		\register_block_type_from_metadata( dirname( __FILE__ ) . '/blocks/tabs-panels-block.json' );
		
		\wp_enqueue_block_style( 'wecodeart/tabs', [
			'handle' => 'wp-block-wecodeart-tabs',
			'src' 	=> $this->get_asset( 'css', 'index' ),
			'path' 	=> $this->get_asset( 'css', 'index', 'directory' ),
			'ver' 	=> wecodeart( 'version' ),
		] );

		\wp_register_script( 
			'wp-block-wecodeart-tabs',
			$this->get_asset( 'js', 'index' ),
			[
				'wp-i18n',
				'wp-data',
				'wp-blocks',
				'wp-editor',
				'wp-element',
				'wp-components',
			],
			wecodeart( 'version' ), 
			true 
		);
	}

	/**
	 * Registers the Tabs block pattern.
	 *
	 * @since 6.6.0
	 * @return void
	 */
	public function register_patterns(): void {
		$patterns = Patterns::get_instance();
		$files = glob( dirname( __FILE__ ) . '/patterns/*.html' );
		if ( $files ) {
			foreach ( $files as $file ) {
				$patterns->register_from_file( wp_parse_args( [
					'theme' 		=> 'wecodeart',
					'categories' 	=> [ 'wecodeart' ],
					'path' 			=> wp_normalize_path( $file ),
				], pathinfo( $file ) ) );
			}
		}
	}

	/**
	 * Get file.
	 *
	 * @return string
	 */
	public function get_asset( string $type, string $name, string $path = 'uri' ): string {
		$file_path = wecodeart_if( 'is_dev_mode' ) ? 'unminified' : 'minified';
		$file_name = wecodeart_if( 'is_dev_mode' ) ? $name . '.' . $type :  $name . '.min.' . $type;
		$file_path = wecodeart_config( 'paths' )[$path] . '/inc/support/modules/tabs/assets/' . $file_path . '/' . $type . '/' . $file_name;
		$file_path = wp_normalize_path( $file_path );

		if( $path === 'uri' ) {
			return esc_url( $file_path );
		}

		return $file_path;
	}
}